default: &default
  adapter: postgresql
  user:
  password:
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bounty_devel

test:
  <<: *default
  database: bounty_test

production:
  <<: *default
  database: bounty
